# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    environment:
      MARIADB_DATABASE: sql_api
      MARIADB_USER: dev_user
      MARIADB_MYSQL_LOCALHOST_USER: local_user
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306
